# Generated by Django 3.2.5 on 2021-07-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_rating_cafe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='cafe_shots/',
        ),
        migrations.AddField(
            model_name='photos',
            name='image',
            field=models.ImageField(default=12, upload_to='cafe_shots/', verbose_name='Фото интерьера'),
            preserve_default=False,
        ),
    ]
